const nav=document.querySelector('.nav');
const menuBtn=document.querySelector('.menu-btn');
const menu=document.querySelector('.menu');
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>20),{passive:true});
menuBtn?.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open);document.body.classList.toggle('menu-open',open)});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const modal=document.getElementById('productModal');
const data={serum:{title:'Uterine Vitality Serum',volume:'150 ml / 5.07 fl oz',img:'assets/serum.webp',alt:'K.L.P Uterine Vitality Serum'},syrup:{title:'Uterine Vitality Syrup',volume:'200 ml / 6.76 fl oz',img:'assets/syrup.webp',alt:'K.L.P Uterine Vitality Syrup'},rexvigor:{title:'REXVOGOR HE-POWER Capsules',volume:'6 × 10 capsules',img:'assets/rexvigor.webp',alt:'REXVOGOR HE-POWER Capsules product packaging'},massageOil:{title:'K.L.P (BUp) Massage Oil',volume:'60 ml',img:'assets/massage-oil.webp',alt:'K.L.P (BUp) Massage Oil'},womanCare:{title:'K.L.P Woman Care Syrup',volume:'200 ml',img:'assets/woman-care.webp',alt:'K.L.P Woman Care Syrup'},purifyGlow:{title:'K.L.P Purify & Glow Blood Purifier Syrup',volume:'200 ml',img:'assets/purify-glow.webp',alt:'K.L.P Purify & Glow Blood Purifier Syrup'},uterineTonic:{title:'K.L.P Uterine Tonic',volume:'200 ml',img:'assets/uterine-tonic.webp',alt:'K.L.P Uterine Tonic'},glowGo:{title:'K.L.P Glow & Go Uterine Tonic',volume:'200 ml',img:'assets/glow-go.webp',alt:'K.L.P Glow & Go Uterine Tonic'},vTightening:{title:'K.L.P V-Tightening Serum',volume:'30 ml / 1 fl oz',img:'assets/v-tightening.webp',alt:'K.L.P V-Tightening Serum'}};
document.querySelectorAll('.details').forEach(btn=>btn.addEventListener('click',()=>{const d=data[btn.dataset.product];document.getElementById('modalImg').src=d.img;document.getElementById('modalImg').alt=d.alt;document.getElementById('modalTitle').textContent=d.title;document.getElementById('modalVolume').textContent=d.volume;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('menu-open')}));
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('menu-open')}
modal.querySelector('.modal-close').addEventListener('click',closeModal);modal.querySelector('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});
document.querySelector('.contact-form')?.addEventListener('submit',e=>{e.preventDefault();const btn=e.currentTarget.querySelector('button');const old=btn.innerHTML;btn.innerHTML='Form ready — connect backend <span>✓</span>';setTimeout(()=>btn.innerHTML=old,2500)});
